# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Axr1lkW-wSSdvyz3K1z8qK2phrskGcFw
"""

import nltk
from nltk.chat.util import Chat,reflections

# Define some reflection pairs for the chatbot
reflections = {
    "i am": "you are",
    "i was": "you were",
    "i": "you",
    "i'm": "you are",
    "i'd": "you would",
    "i've": "you have",
    "i'll": "you will",
    "my": "your",
    "you are": "I am",
    "you were": "I was",
    "you've": "I have",
    "you'll": "I will",
    "your": "my",
    "yours": "mine",
    "you": "me",
    "me": "you"
}

# Define some chat patterns and responses
pairs = [
    [
        r"my name is (.*)",
        ["Hello %1, how can I help you today?",]
    ],
    [
        r"what is your name?",
        ["My name is ChatBot and I'm here to assist you.",]
    ],
    [
        r"how are you ?",
        ["I'm doing good, thank you!",]
    ],
    [
        r"(.*) sorry (.*)",
        ["It's okay, no worries.",]
    ],
    [
        r"quit",
        ["Bye, take care. Have a great day!",]
    ],
]

# Create a Chat instance
chatbot = Chat(pairs, reflections)


# # Define a function to start the chat
def chat():
    print("Hi! I'm ChatBot. How can I assist you today? Type 'quit' to exit.")
    while True:
        user_input = input("You: ")
        response = chatbot.respond(user_input)
        print("ChatBot:", response)
        if user_input == "quit":
            break

# # Start the chat
if __name__ == "__main__":
    nltk.download('punkt')
    chat()